meta_product_name: "j∞rney"
meta_title: "j∞rney | Organisons ensemble votre évènement de groupe !"
meta_description: "j∞rney vous accompagne dans l'organisation de votre évènement de groupe (week-end entre amis, EVG, EVJF, anniversaires, ...)"
meta_image: "fun.png" # should exist in `app/assets/images/`
